"""empty message

Revision ID: 91e28674fade
Revises: 60ecb68b65a8
Create Date: 2017-05-20 11:40:01.261463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91e28674fade'
down_revision = '60ecb68b65a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('story', sa.Column('timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('story', 'timestamp')
    # ### end Alembic commands ###
